name: 'CI'

on:
  push:
    branches:
      - main
  pull_request:
    types: ['opened', 'edited', 'synchronize']

jobs:
  test:
    name: 'Test in: ${{ matrix.os }}, node-${{ matrix.node }}'
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 20]

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: enable corepack
        run: corepack enable

      - name: set up node.js v${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: test
        run: pnpm test

      - name: build
        run: pnpm build

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
